//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

using System;

#nullable enable

namespace UnitsNet.NumberExtensions.NumberToEnthalpyMass
{
    /// <summary>
    /// A number to EnthalpyMass Extensions
    /// </summary>
    public static class NumberToEnthalpyMassExtensions
    {
        /// <inheritdoc cref="EnthalpyMass.FromBtusPerPound(UnitsNet.QuantityValue)" />
        public static EnthalpyMass BtusPerPound<T>(this T value) =>
            EnthalpyMass.FromBtusPerPound(Convert.ToDouble(value));

        /// <inheritdoc cref="EnthalpyMass.FromCaloriesPerGram(UnitsNet.QuantityValue)" />
        public static EnthalpyMass CaloriesPerGram<T>(this T value) =>
            EnthalpyMass.FromCaloriesPerGram(Convert.ToDouble(value));

        /// <inheritdoc cref="EnthalpyMass.FromJoulesPerKilogram(UnitsNet.QuantityValue)" />
        public static EnthalpyMass JoulesPerKilogram<T>(this T value) =>
            EnthalpyMass.FromJoulesPerKilogram(Convert.ToDouble(value));

        /// <inheritdoc cref="EnthalpyMass.FromKilocaloriesPerGram(UnitsNet.QuantityValue)" />
        public static EnthalpyMass KilocaloriesPerGram<T>(this T value) =>
            EnthalpyMass.FromKilocaloriesPerGram(Convert.ToDouble(value));

        /// <inheritdoc cref="EnthalpyMass.FromKilojoulesPerKilogram(UnitsNet.QuantityValue)" />
        public static EnthalpyMass KilojoulesPerKilogram<T>(this T value) =>
            EnthalpyMass.FromKilojoulesPerKilogram(Convert.ToDouble(value));

        /// <inheritdoc cref="EnthalpyMass.FromMegajoulesPerKilogram(UnitsNet.QuantityValue)" />
        public static EnthalpyMass MegajoulesPerKilogram<T>(this T value) =>
            EnthalpyMass.FromMegajoulesPerKilogram(Convert.ToDouble(value));

    }
}
