//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

using System;

#nullable enable

namespace UnitsNet.NumberExtensions.NumberToInverseTemperature
{
    /// <summary>
    /// A number to InverseTemperature Extensions
    /// </summary>
    public static class NumberToInverseTemperatureExtensions
    {
        /// <inheritdoc cref="InverseTemperature.FromInverseDegreesCelsius(UnitsNet.QuantityValue)" />
        public static InverseTemperature InverseDegreesCelsius<T>(this T value) =>
            InverseTemperature.FromInverseDegreesCelsius(Convert.ToDouble(value));

        /// <inheritdoc cref="InverseTemperature.FromInverseDegreesFahrenheit(UnitsNet.QuantityValue)" />
        public static InverseTemperature InverseDegreesFahrenheit<T>(this T value) =>
            InverseTemperature.FromInverseDegreesFahrenheit(Convert.ToDouble(value));

        /// <inheritdoc cref="InverseTemperature.FromInverseDegreesRankine(UnitsNet.QuantityValue)" />
        public static InverseTemperature InverseDegreesRankine<T>(this T value) =>
            InverseTemperature.FromInverseDegreesRankine(Convert.ToDouble(value));

        /// <inheritdoc cref="InverseTemperature.FromInverseKelvins(UnitsNet.QuantityValue)" />
        public static InverseTemperature InverseKelvins<T>(this T value) =>
            InverseTemperature.FromInverseKelvins(Convert.ToDouble(value));

    }
}
