//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated (once) by \generate-code.bat, but will not be
//     regenerated when it already exists. The purpose of creating this file is to make
//     it easier to remember to implement all the unit conversion test cases.
//
//     Whenever a new unit is added to this quantity and \generate-code.bat is run,
//     the base test class will get a new abstract property and cause a compile error
//     in this derived class, reminding the developer to implement the test case
//     for the new unit.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run GeneratUnits.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.


using System;
using Xunit;

namespace UnitsNet.Tests.CustomCode
{
    public class MolarMassTests : MolarMassTestsBase
    {
        protected override bool SupportsSIUnitSystem => false;
        protected override double CentigramsPerMoleInOneKilogramPerMole => 1e5;
        protected override double DecagramsPerMoleInOneKilogramPerMole => 1e2;
        protected override double DecigramsPerMoleInOneKilogramPerMole => 1e4;
        protected override double GramsPerMoleInOneKilogramPerMole => 1e3;
        protected override double HectogramsPerMoleInOneKilogramPerMole => 10;
        protected override double KilogramsPerMoleInOneKilogramPerMole => 1;
        protected override double KilopoundsPerMoleInOneKilogramPerMole => 2.2046226218487757e-3;
        protected override double MegapoundsPerMoleInOneKilogramPerMole => 2.2046226218487757e-6;
        protected override double MicrogramsPerMoleInOneKilogramPerMole => 1e9;
        protected override double MilligramsPerMoleInOneKilogramPerMole => 1e6;
        protected override double NanogramsPerMoleTolerance => 1e-3;
        protected override double NanogramsPerMoleInOneKilogramPerMole => 1e12;
        protected override double PoundsPerMoleInOneKilogramPerMole => 2.2046226218487757;

        protected override double CentigramsPerKilomoleInOneKilogramPerMole => 1.0e8;

        protected override double DecagramsPerKilomoleInOneKilogramPerMole => 1.0e5;

        protected override double DecigramsPerKilomoleInOneKilogramPerMole => 1.0e7;

        protected override double GramsPerKilomoleInOneKilogramPerMole => 1.0e6;

        protected override double HectogramsPerKilomoleInOneKilogramPerMole => 1.0e4;

        protected override double KilogramsPerKilomoleInOneKilogramPerMole => 1.0e3;

        protected override double KilopoundsPerKilomoleInOneKilogramPerMole => 2.204623;

        protected override double MegapoundsPerKilomoleInOneKilogramPerMole => 2.204623e-3;

        protected override double MicrogramsPerKilomoleInOneKilogramPerMole => 1.0e12;

        protected override double MilligramsPerKilomoleInOneKilogramPerMole => 1.0e9;

        protected override double NanogramsPerKilomoleInOneKilogramPerMole => 1.0e15;

        protected override double PoundsPerKilomoleInOneKilogramPerMole => 2204.623;
    }
}
