//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

using UnitsNet.NumberExtensions.NumberToEnthalpyMolar;
using Xunit;

namespace UnitsNet.Tests
{
    public class NumberToEnthalpyMolarExtensionsTests
    {
        [Fact]
        public void NumberToBTUsPerPoundTest() =>
            Assert.Equal(EnthalpyMolar.FromBTUsPerPound(2), 2.BTUsPerPound());

        [Fact]
        public void NumberToCaloriesPerMoleTest() =>
            Assert.Equal(EnthalpyMolar.FromCaloriesPerMole(2), 2.CaloriesPerMole());

        [Fact]
        public void NumberToJoulesPerKilomoleTest() =>
            Assert.Equal(EnthalpyMolar.FromJoulesPerKilomole(2), 2.JoulesPerKilomole());

        [Fact]
        public void NumberToJoulesPerMoleTest() =>
            Assert.Equal(EnthalpyMolar.FromJoulesPerMole(2), 2.JoulesPerMole());

        [Fact]
        public void NumberToKilojoulesPerKilomoleTest() =>
            Assert.Equal(EnthalpyMolar.FromKilojoulesPerKilomole(2), 2.KilojoulesPerKilomole());

        [Fact]
        public void NumberToKilojoulesPerMoleTest() =>
            Assert.Equal(EnthalpyMolar.FromKilojoulesPerMole(2), 2.KilojoulesPerMole());

        [Fact]
        public void NumberToMegajoulesPerMoleTest() =>
            Assert.Equal(EnthalpyMolar.FromMegajoulesPerMole(2), 2.MegajoulesPerMole());

    }
}
